export let _mappings = {
"tt": "trí tuệ|tu tập|trở thành|thực tế|trong tâm|ta thấy|thế thì|thông tin|trạng thái|tiếp tục|tập trung|tiếp theo|tinh tấn|thông thường|thái tâm|thỉnh thoảng|ta thực|tưởng tượng|thế thôi|ta thường|tâm tham|trực tiếp|thầy thấy|ta tu|tâm từ|thanh thản|tôn trọng|tư thế|thì tự|trân trọng|trong thân|ta tự|từ trong|tâm thiện|tự tin|trưởng thành|từ trước|thân tâm",
"cn": "chánh niệm|con người|có những|cảm nhận|của người|cả những|cái này|của nó|chấp nhận|cái người|cho nó|cho người|cũng như|có người|chúng nó|chỗ nào|cãi nhau|còn nếu|càng ngày|cộng nghiệp|có nhiều|cách nhìn|chỗ này|của ngài|chuyên nghiệp|chục năm|cho những|cái nào|càng nhiều|cái nghiệp|cách nào|cái nhà|chăng nữa|cái nhân",
"cc": "của chúng|có cái|cho chúng|cũng có|có chánh|chỉ có|chắc chắn|cái cảm|cuối cùng|các cảm|chỉ cần|chẳng có|con cái|của con|cả cuộc|cho con|cái chuyện|cũng chẳng|câu chuyện|cả các|cho cái|cả chúng|cái cách|của cuộc|của cái|chất của|cái chỗ|cứ cái|chưa chắc|chính cái|cái chúng|cả cái|cũng chỉ|có cảm|cái câu|của các",
"tc": "tất cả|thì chúng|ta có|ta cũng|thậm chí|trong cuộc|thì cái|ta chỉ|tâm của|thấy cái|tâm chúng|trong cái|ta cảm|trẻ con|thì có|ta cứ|theo cái|tìm cách|thầy cũng|thì cũng|thầy cười|tiêu chuẩn|thì con|từ cái|thiền chỉ|ta càng|thấy có|thành công|thầy có|tiêu cực|tích cực|ta còn|thân của|tính cách|thường chúng",
"tn": "thế nào|thế này|thế nên|thể nào|tự nhiên|thì nó|thế nhưng|trách nhiệm|tâm nó|thầy nói|ta nghĩ|thì người|ta nhìn|tất nhiên|tốt nhất|thấy nó|trong những|trọng nhất|thân này|từ những|ta nói|tí nào|tạo nên|trải nghiệm|thứ nhất|thấy những|tiềm năng|thì những|thứ nó|thế nó|thất niệm|ta ngồi",
"nc": "những cái|nó cũng|nó có|nó chỉ|người có|nào cũng|nói chuyện|ngày càng|nên chúng|ngay cả|nào cả|nếu chúng|nó còn|những cảm|người cười|người chúng|nghĩ của|như chúng|nào chúng|nhiều cái|như cái|nói chung|nhìn cái|này có|nó càng|nhạy cảm|nên cái",
"td": "thay đổi|thái độ|ta đã|trong đó|thứ đó|ta đang|tự động|thấy được|ta đi|ta đều|trong đầu|tốt đẹp|tác động|thầy dạy|tác dụng|thức được|thành đạt|thầy đã|thời đức|tận dụng|tu được|ta đến|tương đối|tiếng đồng|ta đọc|thì dần",
"mc": "một cái|mà chúng|một cách|mình có|mình cũng|một con|mình chỉ|mà có|một chút|mà cái|một câu|mình cảm|mình cứ|mới có|một cảm|một cuộc|mình chưa|mình còn|mà con|mình cần|mấy chục|mình cho|mình chẳng|mình cả|một chỗ",
"ct": "chúng ta|có thể|cái tâm|cảm thấy|cũng thế|căng thẳng|cái thân|cơ thể|của tâm|có trí|của thầy|chư tăng|chân thật|cần thiết|cái tôi|các thứ|cái thời|con thấy|có tác|cũng thấy|cái thái|của thân|chạy trốn|cách thực",
"nt": "như thế|người ta|nhìn thấy|những thứ|ngồi thiền|nhiều thứ|người tu|này thì|nó trở|người thực|người trí|nó tạo|nó thành|người thân|này thế|như thầy|niệm thì|nhiều thì|nhiều thời|nguyên tắc|nên tại|nữa thì",
"tl": "tức là|thế là|ta làm|ta là|trở lại|thả lỏng|trong lúc|ta lại|tương lai|thường là|tâm lý|thì lúc|ta luôn|thể là|thấy là|tâm linh|trả lời|thể làm|thật là|thiền là|tu là|toàn là|thì làm|tĩnh lặng|tiên là",
"nn": "những người|nhiều người|người nào|này nó|người này|nhiều nhất|người như|ngày nào|nguyên nhân|ngôn ngữ|nó như|nghĩ như|như này|nghỉ ngơi|nhiêu năm|nhẹ nhàng|này nọ|người nói|nên nó|nhiên nó|này này",
"nl": "nó là|nhất là|nên là|như là|năng lượng|này là|ngay lập|nó làm|nào là|nó lại|nhiên là|nữa là|niệm là|nghĩ là|nói là|nghĩa là|nhiều lần|những lúc|người là|những lời|ngược lại|nó luôn",
"mt": "mọi thứ|mình thấy|một thời|mình thì|một tí|mà thầy|mình tu|mà thực|mới thấy|mình thực|mình thích|mình trong|một tiếng|mục tiêu|mình trở|mình tự|mà trong|mình tìm|một trong",
"tk": "ta không|thì không|trong khi|thầy không|trước khi|toàn không|toàn khác|thứ khác|tự kỷ|tự khắc|thấy không|thoát khỏi|trước kia|thế kia|thế không|tà kiến|thì khi|trong kinh",
"dc": "được cái|để cho|để chúng|đó chúng|đừng có|đời của|đó có|đến cái|đều có|động của|đang có|đã có|đó cũng|dành cho|đứa con|đến chùa|đầu chúng|độ của|động cơ|dạy cho|do cái",
"nm": "nhưng mà|nếu mà|nếu mình|người mà|nào mà|như một|ngày mai|nó mới|nào mình|người mình|nhưng mình|nói một|như mình|nên mình|này mình|ngã mạn|nhắc mình|nhiên mình",
"tm": "tâm mình|thân mình|thì mình|thoải mái|ta mới|thành một|thấy mình|trong một|trong mình|thấy một|thế mà|thì mới|trước mặt|ta muốn|trong mọi|theo một|thêm một",
"cd": "cái đó|cuộc đời|cái điều|con đường|cho đến|cái đấy|có được|chỗ đó|chuyện đó|cúng dường|của đức|có đủ|cách để|có điều|chịu đựng|cũng được|cộng đồng|chỉ đơn",
"ctn": "chúng ta nghĩ|chúng ta nhìn|cái thân này|chúng ta ngồi|chịu trách nhiệm|chúng ta nó|chúng ta nghe|chúng ta nên|chúng ta nói|có trách nhiệm",
"dd": "điều đó|dần dần|đạt được|đến đây|được điều|đắc đạo|đó để|dễ dàng|đến đâu|đi đến|dễ duôi|đau đớn|đang đi|đối diện|đám đông|đạt đến|độ đúng",
"mn": "mọi người|một người|mình nó|mà nó|mình nhìn|mình nghĩ|mình như|mà người|một ngày|mình nói|mình ngồi|mỗi người|mà những|mà nếu|mình nghe",
"nd": "nào đó|người đó|những điều|nghĩ đến|nó đang|nhận được|người đều|nhất định|nhân duyên|nói dối|người đã|nó đi|nó đến|nó đã|nào để|nghĩ đó",
"ctt": "chúng ta thấy|chúng ta thực|có trí tuệ|chúng ta thường|chúng ta tu|chúng ta tự|chúng ta tập|chúng ta tiếp|chúng ta tìm|các trạng thái",
"dt": "đó thì|đầu tiên|đức tin|đi tìm|đã từng|điện thoại|đầu tư|đến tận|định tâm|đối tượng|đó thôi|được thì|đi theo|đồng tiền|đầu từ|đi tu",
"ctc": "chúng ta có|chúng ta cũng|chúng ta chỉ|chúng ta cảm|chúng ta cứ|chúng ta càng|cái tâm của|chúng ta cần|chúng ta còn|chúng ta chưa",
"vc": "và chúng|vô cùng|và cái|vào cái|với cái|vì cái|vì chúng|việc của|vẫn còn|về cái|vậy chúng|với cả|với chính|với con|vẫn có|và có",
"ctd": "chúng ta đã|chúng ta đang|chúng ta đều|chúng ta đi|có tác dụng|chúng ta đến|cái thái độ|chúng ta đọc|chúng ta được|chúng ta để",
"lc": "là cái|là chúng|làm cho|lựa chọn|là có|là con|làm cái|là chánh|là cảm|là các|luôn có|lại cái|lực của|là chỉ|là của|là cách",
"kt": "không thể|kiến thức|không thích|kiếm tiền|không thấy|kiểm tra|kiếp trước|không thực|không tu|khóa thiền|khi thực|khi tu",
"kn": "khác nhau|khả năng|kiên nhẫn|không nói|không nên|khi nó|không nhìn|khi nào|kinh nghiệm|khái niệm|khi người|không nghĩ",
"vn": "vậy nên|với những|với người|và nó|với nhau|việt nam|với nó|việc này|vì nó|về nhà|và những|vào những|và người|vô ngã",
"dl": "đó là|đấy là|đây là|để làm|đang làm|đi làm|dừng lại|đều là|đến lúc|đó làm|động lực|định là|đảnh lễ|đầu là|đã làm",
"cm": "của mình|có một|cho mình|cả mọi|cả một|cái mình|chính mình|cha mẹ|con mình|cứ một|cái mà|cho một|có mặt|cùng một",
"dm": "để mà|đó mình|đến mức|đủ mọi|được một|để mình|đến một|dính mắc|đó mà|đời mình|đầu mình|đó mới|đến mình|đề mục",
"vt": "vô thức|vô thường|vì thế|vào trong|và tâm|với thầy|vị thầy|với thực|vị thánh|vi tế|vị tỳ|với tâm|vị thiền",
"nct": "nên chúng ta|nếu chúng ta|người chúng ta|như chúng ta|nào chúng ta|nó có thể|người có trí|ngày chúng ta",
"lt": "lập tức|liên tục|là tốt|là tâm|là tự|lý tưởng|làm thế|là thầy|là trong|là tu|lung tung|lòng tin|là thực",
"tct": "thì chúng ta|ta có thể|tâm chúng ta|ta cảm thấy|thường chúng ta|thế chúng ta|thân chúng ta|ta cũng thế",
"ml": "mình là|mình làm|một lúc|mới là|một lần|một là|mình lại|mang lại|muốn làm|mình luôn|một loại|mà làm",
"ck": "chứ không|cũng không|cực kỳ|có khi|chánh kiến|cung kính|có khả|cái kia|con không|cái khổ|còn khi",
"mm": "mà mình|mình mới|mình muốn|mỗi một|mệt mỏi|mong muốn|mình một|mạnh mẽ|mặt mình|mình mà|một mình",
"dn": "đó nó|được những|dụ như|đang ngồi|được nữa|duy nhất|được như|được nó|điều nữa|để nó|đến những",
"md": "mình đang|mình đã|một điều|mặc dù|mình đi|mức độ|mục đích|miến điện|mình để|mình được|mất đi",
"ld": "lúc đó|làm được|là đúng|là do|là dễ|là để|lý do|là điều|là đơn|làm điều|lâu dài|là đủ|là đi",
"ln": "là những|là nhiều|là người|là nó|lúc nào|là như|lời nói|làm như|làm những|lớn nhất|là nhanh",
"kc": "không có|khi chúng|không cần|không còn|khó chịu|không chịu|khi có|kể cả|khẩn cấp|khỏi cái",
"nk": "người khác|nó không|người không|nếu không|nhiều khi|nó khác|này không|người kia|như không",
"th": "thực hành|thứ hai|thể hiện|tìm hiểu|tu hành|trường hợp|ta hiểu|thì họ|tốt hơn|trong hiện",
"ts": "tại sao|ta sẽ|thực sự|thiền sinh|thật sự|thiền sư|ta sống|tâm sân|tài sản|thì sẽ|tâm si",
"pt": "phát triển|phật tử|phụ thuộc|phải thực|phát từ|phải tự|phương tiện|phải trả|phải tìm",
"ht": "hoàn toàn|hành thiền|hơi thở|hiện tại|học trò|hưởng thụ|hết tất|hứng thú|hành theo",
"cp": "cần phải|cũng phải|cái phước|cứ phải|chi phối|cái phần|con phải|có phải|chất phác",
"cnt": "cũng như thế|con người ta|của người ta|cho người ta|cả những thứ|chánh niệm thì",
"vm": "và mình|với mình|với một|vì mình|vào một|việc mình|về mình|và một|và mọi|về mặt",
"hn": "hệt như|hôm nay|hạn như|hàng ngày|hiện nay|hầu như|hơn người|hơn nữa|hình như",
"nv": "như vậy|những việc|nó vẫn|nhiệm vụ|nghĩ về|nhiều việc|nói với|nhiều và|nó và",
"tv": "ta vẫn|thuộc vào|tin vào|thuộc về|trong vô|thầy và|thế và|thân và|thở vào",
"mct": "mà chúng ta|mình có thể|mình cảm thấy|mới có thể|một cái tâm|một cách tự",
"tr": "ta rất|thấy rằng|thấy rất|thực ra|tạo ra|thấy rõ|thoát ra|thở ra|thì rất",
"ctl": "chúng ta làm|chúng ta là|chúng ta lại|có thể là|chúng ta luôn|có thể làm",
"kd": "không được|không để|không đủ|kinh điển|khi đi|khi đó|không dám|khi đến",
"ntc": "người ta có|người ta cũng|nhìn thấy cái|như thế chúng|người thân của",
"nmc": "nhưng mà chúng|nếu mà chúng|nhưng mà cái|nhưng mà có|nào mình cũng",
"cmn": "cả mọi người|của mình nó|có một người|cho mọi người|của mọi người",
"tg": "thời gian|thư giãn|trực giác|tỉnh giác|tuệ giác|thế giới|thế gian",
"lm": "là một|là mình|làm mình|làm một|lúc mình|là mạnh|la mật|lại mình",
"vct": "và chúng ta|vì chúng ta|vậy chúng ta|việc chúng ta|với chúng ta",
"bgc": "bao giờ cũng|bây giờ chúng|bao giờ chúng|bao giờ có|bây giờ có",
"cv": "cái việc|các vị|công việc|chính vì|cách vô|cùng với|chuyện với",
"dct": "để chúng ta|đó chúng ta|đầu chúng ta|đời chúng ta|đây chúng ta",
"ntn": "như thế nào|như thế này|như thế nó|người ta nói|như thế nhưng",
"hd": "hiểu được|hành động|hoạt động|hướng đến|hướng dẫn|hành được",
"mv": "một vị|mình vẫn|một việc|mình và|mọi việc|một vài|mình với",
"tht": "thực hành thiền|trong hiện tại|thực hành theo|ta hoàn toàn",
"tb": "ta biết|ta bắt|toàn bộ|tâm bất|ta bị|thầy bảo|thứ ba|từ bé",
"gc": "gì cả|giờ chúng|giờ cũng|giúp cho|gì cũng|giờ có|gì chúng",
"ttct": "thế thì chúng ta|trong tâm chúng ta|thông thường chúng ta",
"ch": "chẳng hạn|của họ|cơ hội|cái hình|cái hiểu|có hiểu|cao hơn",
"lmc": "là một cái|là một cảm|là mình có|là một cách|làm một cái",
"ctkc": "chúng ta không có|chúng ta không cần|chúng ta không chịu",
"cnc": "càng ngày càng|cả những cái|có những cái|con người chúng",
"nmk": "nhưng mà khi|nhưng mà không|nếu mà không|nếu mình không",
"cbtm": "chính bản thân mình|cho bản thân mình|của bản thân mình",
"cl": "chỉ là|cũng là|cái là|chắn là|chính là|còn lại|cần làm",
"cs": "cuộc sống|có sự|cái sự|cư sĩ|cái suy|cơn sân|cách suy",
"cttt": "chúng ta tu tập|các trạng thái tâm|chúng ta trở thành",
"ctcn": "chúng ta cảm nhận|chúng ta chánh niệm|có thể cảm nhận",
"bc": "bất cứ|biết cái|bằng cách|bản chất|bên cạnh|bước chân",
"dk": "đúng không|đau khổ|đôi khi|điều kiện|đó không|đến khi",
"ll": "luôn luôn|là lớn|lại là|là làm|là lúc|là lâu|lo lắng",
"nr": "nó rất|nghĩ rằng|người rất|nói rằng|nhận ra|nhìn ra",
"ctcc": "chúng ta có chánh|chúng ta cũng có|chúng ta chỉ cần",
"ctct": "chúng ta có thể|chúng ta cảm thấy|chúng ta cũng thế",
"ntt": "như thế thì|nó trở thành|như thế thôi|người trí tuệ",
"mb": "mình biết|mình bị|mình bắt|mới biết|mới bắt|một bài",
"tcct": "tâm của chúng ta|tất cả chúng ta|thậm chí chúng ta",
"cct": "của chúng ta|cho chúng ta|cả chúng ta|cái chúng ta",
"tlct": "tức là chúng ta|thường là chúng ta|thế là chúng ta",
"nnt": "người như thế|nghĩ như thế|nó như thế|nói như thế",
"tnt": "thì người ta|thế này thế|thế nên tại|tục như thế",
"dvct": "do vậy chúng ta|đối với chúng ta|đó và chúng ta",
"tcm": "tất cả mọi|tâm của mình|thân của mình|ta có một",
"lnt": "là như thế|là người ta|làm như thế|lần như thế",
"tnl": "thế nên là|thế nào là|tất nhiên là|tốt nhất là",
"rl": "rất là|rèn luyện|rồi là|ra là|rằng là|rất lớn",
"ccg": "cái cảm giác|các cảm giác|có cái gì|cứ cái gì",
"km": "khi mình|khi mà|không muốn|khuôn mặt|khi một",
"sn": "suy nghĩ|số người|suốt ngày|sau này|sống như",
"st": "sẽ thấy|sự thật|sự thay|sự tu|sự thực|sự tự",
"ntk": "người ta không|như thế không|những thứ khác",
"dlc": "đó là cái|đấy là cái|đó là chúng|đó làm cho",
"mk": "mình không|mà không|mà khi|mình khổ|mỗi khi",
"cmcg": "có một cái gì|cứ một cái gì|có một cảm giác",
"ttm": "trở thành một|trong tâm mình|thân tâm mình",
"cb": "cái bản|chính bản|có biết|chưa bao|cho bản",
"ttc": "thế thì chúng|trí tuệ của|trong tâm chúng",
"nth": "người thực hành|người tu hành|nó thể hiện",
"cbt": "chính bản thân|cho bản thân|của bản thân",
"mcn": "một con người|mấy chục năm|mình cảm nhận",
"ms": "mình sẽ|một số|một sự|mình sống|mình sân",
"bt": "bản thân|bình thường|bất thiện|bên trong",
"cg": "cái gì|cảm giác|cố gắng|có gì|cũng giống",
"cth": "chúng ta hiểu|chúng ta hãy|chúng ta hoàn",
"mkc": "mình không có|mà không có|mình không cần",
"mnc": "mọi người cười|mọi người có|một người có",
"kb": "không biết|không bao|khác biệt|không bị",
"mnt": "mình như thế|mà người ta|mình nhìn thấy",
"lk": "là không|là khó|là khi|là khổ|lại không",
"sc": "sống của|sự chú|sẽ có|sao chúng|suốt cả",
"gd": "gì đó|gia đình|giác đó|gì đến|giai đoạn",
"ctm": "chúng ta mới|cái tâm mình|chúng ta muốn",
"cttx": "chúng ta thường xuyên|chúng ta tiếp xúc",
"ctpt": "chúng ta phát triển|chúng ta phải thực",
"ctkn": "chúng ta không nhìn|chúng ta không nên",
"ttt": "trạng thái tâm|ta tu tập|triển trí tuệ",
"ctnv": "chịu trách nhiệm về|có trách nhiệm với",
"ctb": "chúng ta biết|chúng ta bắt|chúng ta bị",
"ctht": "chúng ta hoàn toàn|chúng ta hành thiền",
"tdd": "thì dần dần|thái độ đúng|thay đổi được",
"btct": "bản thân chúng ta|bình thường chúng ta",
"qt": "quan trọng|quá trình|quay trở|quan tâm",
"mcd": "một cái điều|một cách đơn|một cuộc đời",
"ctkb": "chúng ta không biết|chúng ta không bao",
"dvn": "do vậy nên|đối với người|đối với những",
"tcc": "tâm của chúng|tất cả chúng|tất cả các",
"tnm": "thế nhưng mà|tự nhiên mình|thể nào mà",
"cts": "chúng ta sẽ|chúng ta sống|chúng ta sử",
"tmc": "thành một cái|thành một con|ta mới có",
"nctk": "nếu chúng ta không|nên chúng ta không",
"rln": "rất là nhiều|rất là nhanh|rất là nguy",
"cthd": "chúng ta hướng đến|chúng ta hiểu được",
"cnl": "chánh niệm là|cái này là|có những lúc",
"ctkh": "chúng ta không hề|chúng ta không hiểu",
"thnt": "thực hành như thế|trường hợp như thế",
"pn": "phiền não|phật nói|phải như|phải nói",
"nh": "nhiều hơn|ngày hôm|nguy hiểm|nó hoàn",
"kbgc": "không bao giờ có|không bao giờ chúng",
"kplm": "không phải là mình|không phải là một",
"ctcp": "chúng ta cũng phải|chúng ta cần phải",
"cttr": "chúng ta thấy rằng|chúng ta thấy rất",
"gt": "giải thoát|giá trị|giải thích|gì thì",
"ls": "làm sao|là sự|lần sau|là sai|lúc sau",
"ttmc": "trở thành một con|trở thành một cái",
"bn": "bao nhiêu|bên ngoài|bản ngã|biết nó",
"vctk": "vì chúng ta không|và chúng ta không",
"tktn": "ta không thể nào|thì không thể nào",
"nnk": "những người khác|những người không",
"vbtm": "về bản thân mình|với bản thân mình",
"ctdd": "chúng ta đạt được|chúng ta đến đây",
"kl": "không làm|khởi lên|kỷ luật|khác là",
"tkbg": "ta không bao giờ|thì không bao giờ",
"lcm": "làm cho mình|là của mình|là có một",
"sk": "sau khi|sẽ không|sức khỏe|sự khác",
"nmct": "nhưng mà chúng ta|nếu mà chúng ta",
"bgct": "bây giờ chúng ta|bao giờ chúng ta",
"tctc": "thì chúng ta cũng|thì chúng ta có",
"nttm": "như thế thì mình|nó trở thành một",
"ncgm": "những cái gì mình|những cái gì mà",
"dp": "đức phật|đa phần|đạo phật|để phát",
"ttl": "tu tập là|trí tuệ là|tiếp theo là",
"cctc": "của chúng ta cũng|của chúng ta có",
"dg": "đơn giản|đánh giá|điều gì|đó gọi",
"hlct": "hoặc là chúng ta|hai là chúng ta",
"lcg": "là cái gì|làm cái gì|là cảm giác",
"gn": "giống như|ghi nhận|gì nữa|giờ nó",
"mnnd": "một ngày nào đó|một người nào đó",
"sm": "sao mà|sao mình|sức mạnh|sau một",
"ctcm": "cái tâm của mình|chúng ta có một",
"dr": "đó rất|được rất|diễn ra|điều rất",
"trl": "thấy rất là|ta rất là|thì rất là",
"ntct": "như thế chúng ta|người ta có thể",
"vs": "vị sư|vì sao|vô số|về sau|với sự",
"nlct": "nên là chúng ta|nhất là chúng ta",
"dvnc": "do vậy nên chúng|do vậy nên cái",
"ctrl": "chúng ta rất là|cảm thấy rất là",
"dlm": "đấy là một|đó là một|đó là mình",
"lctc": "là chúng ta có|là chúng ta cũng",
"lctd": "là chúng ta đã|là chúng ta đang",
"tctl": "thì chúng ta lại|ta có thể làm",
"lv": "làm việc|là vô|là việc|lại với",
"tp": "ta phải|trình pháp|thuyết pháp",
"ctdc": "chúng ta đều có|chúng ta đã có",
"kqt": "không quan trọng|kỳ quan trọng",
"htk": "hoàn toàn không|hoàn toàn khác",
"lmcg": "là một cảm giác|là một cái gì",
"hk": "hay không|họ không|hiểu không",
"mctc": "mà chúng ta có|mà chúng ta cứ",
"mkb": "mình không biết|mà không biết",
"kth": "khi thực hành|không thực hành",
"mkp": "mình không phải|mà không phải",
"lntn": "là như thế này|là như thế nào",
"clmc": "chỉ là một cái|chỉ là một cảm",
"cnk": "của người khác|cho người khác",
"cdgl": "chỉ đơn giản là|cái đó gọi là",
"cdlc": "cái đó là cái|cái đấy là cái",
"vcm": "việc của mình|với chính mình",
"dv": "do vậy|đối với|đó và|đến với",
"hl": "hoặc là|hai là|hay là|hơn là",
"cnd": "cảm nhận được|chấp nhận được",
"bmd": "biết mình đang|bên miến điện",
"knt": "không nhìn thấy|khi người ta",
"pb": "phải biết|phước báu|phật bảo",
"cht": "cách hoàn toàn|chẳng hạn thì",
"btm": "bản thân mình|bên trong mình",
"dlmc": "đấy là một cái|đó là một cái",
"tq": "thói quen|trong quá|ta quan",
"mdn": "một điều nữa|mình đang ngồi",
"cdc": "cuộc đời của|cuộc đời chúng",
"kcc": "không có cái|không có chánh",
"ncg": "những cái gì|những cảm giác",
"sl": "sai lầm|sự là|sự lựa|sẽ làm",
"ph": "phát hiện|pháp hành|phù hợp",
"tgd": "trong gia đình|thời gian đó",
"ctp": "chúng ta phải|chúng ta phát",
"tmn": "tâm mình nó|thành một người",
"ccn": "có chánh niệm|của con người",
"cdg": "chỉ đơn giản|cách đơn giản",
"tkb": "ta không biết|ta không bao",
"csn": "cái suy nghĩ|cách suy nghĩ",
"lcn": "là chánh niệm|là con người",
"ncm": "những cái mà|nghĩ của mình",
"mch": "một cách hoàn|một cái hình",
"msn": "một số người|mình suy nghĩ",
"lmk": "là mình không|làm mình khổ",
"nb": "người bình|nó bắt|niết bàn",
"qtl": "quay trở lại|quan trọng là",
"dh": "định hướng|đòi hỏi|đồng hồ",
"vmn": "và mọi người|với một người",
"cvt": "chính vì thế|cách vô thức",
"lmn": "là một người|là mọi người",
"ttv": "tập trung vào|từ trong vô",
"nmm": "nếu mà mình|nhưng mà mình",
"bgm": "bây giờ mình|bao giờ mình",
"lnc": "là những cái|lúc nào cũng",
"ctr": "chúng ta rất|cảm thấy rất",
"ddt": "điều đầu tiên|điều đó thì",
"tvt": "trong vô thức|thân và tâm",
"ds": "được sự|đọc sách|đằng sau",
"cnm": "con người mình|còn nếu mà",
"mln": "mình là người|một lúc nào",
"vtt": "với thực tế|vị thánh tăng",
"ckn": "có khả năng|cái khả năng",
"nmn": "nhưng mà nó|nhưng mà nếu",
"rn": "rất nhiều|ra những|ra nó",
"gct": "giờ chúng ta|gì chúng ta",
"ccd": "cả cuộc đời|của cuộc đời",
"dln": "đó là những|đều là những",
"cr": "có rất|cũng rất|cách rất",
"nkc": "nó không có|nó không còn",
"ntd": "những thứ đó|nó thay đổi",
"mh": "mình hiểu|mà họ|một hình",
"dvm": "đối với một|đối với mình",
"tcn": "tất cả những|ta cảm nhận",
"rm": "ra một|rằng mình|ra mình",
"at": "anh ta|ảo tưởng|ấn tượng",
"plm": "phải là mình|phải là một",
"mbd": "mới bắt đầu|mình bắt đầu",
"ott": "ở trong tâm|ở trong thân",
"pl": "phải là|phải làm|pháp là",
"mts": "mà tại sao|mình thực sự",
"cln": "chỉ là những|cứ lúc nào",
"cy": "chú ý|có ý|cũng y|cái ý",
"tsm": "tại sao mình|tại sao mà",
"crl": "cũng rất là|cách rất là",
"nts": "người ta sẽ|nên tại sao",
"tnc": "tí nào cả|thế nên chúng",
"mcg": "một cái gì|một cảm giác",
"tlc": "tức là cái|tức là chúng",
"ntv": "như thế và|người ta vẫn",
"lmd": "là mình đang|là mình đã",
"bcc": "bất cứ cái|bản chất của",
"bvc": "bởi vì chúng|bởi vì cái",
"tld": "thì lúc đó|thể làm được",
"sv": "so với|sự việc|sách vở",
"cx": "cảm xúc|cái xấu|cái xe",
"ncl": "nó chỉ là|nói chung là",
"cdt": "cho đến tận|có đức tin",
"hr": "hơn rất|hiện ra|họ rất",
"tbd": "ta bắt đầu|thì bắt đầu",
"od": "ở đây|ở đó|ở đâu|ở đấy",
"rd": "ra được|rất dễ|rất đơn",
"lmv": "làm một việc|là một vị",
"lct": "là chúng ta|là cái tâm",
"nrl": "nó rất là|người rất là",
"stt": "sự tu tập|sẽ trở thành",
"clm": "chỉ là một|cũng là một",
"gm": "giờ mình|gì mình|gì mà",
"rll": "rất là lớn|rất là lâu",
"cgd": "cái gì đó|cảm giác đó",
"cnbt": "con người bình thường",
"ptcn": "phát triển chánh niệm",
"cmc": "có một cái|cứ một cái",
"oc": "ở chỗ|ông chồng|ở cái",
"cvd": "cái việc đó|có vấn đề",
"cgc": "cái gì cả|cái gì cũng",
"rlk": "rất là khó|rất là khổ",
"pgnt": "phật giáo nguyên thủy",
"cmv": "có một vị|của mình và",
"dgl": "đơn giản là|đó gọi là",
"tx": "thường xuyên|tiếp xúc",
"cgm": "cái gì mình|cái gì mà",
"mtn": "mọi thứ nó|một tí nào",
"mnbt": "một người bình thường",
"rnth": "rất nhiều trường hợp",
"nlc": "nó làm cho|nó là cái",
"nttt": "những trạng thái tâm",
"lms": "là mình sẽ|là một sự",
"thcn": "thực hành chánh niệm",
"vl": "vậy là|và lúc|vẫn là",
"rld": "rất là dễ|rất là đơn",
"cdl": "cái đó là|cái đấy là",
"vh": "văn hóa|và họ|với họ",
"ad": "ấn độ|áp đặt|áp dụng",
"gl": "gọi là|gì là|giản là",
"rnnl": "rất nhiều năng lượng",
"bl": "biết là|bảo là|ba la",
"vd": "vấn đề|ví dụ|việc đó",
"vqtn": "việc quan trọng nhất",
"mckp": "mình chứ không phải",
"tvdk": "thương vô điều kiện",
"ttcc": "trong tâm của chúng",
"ctqd": "chúng ta quyết định",
"tvcm": "thật với chính mình",
"kptn": "không phải tự nhiên",
"tmcn": "thành một con người",
"tcsc": "trong cuộc sống của",
"kccn": "không có chánh niệm",
"nnnt": "những người như thế",
"dvnn": "đối với những người",
"pttl": "phát triển tâm linh",
"ctkp": "chúng ta không phải",
"kh": "không hề|không hiểu",
"ttmn": "trở thành một người",
"kptv": "không phụ thuộc vào",
"rntg": "rất nhiều thời gian",
"no": "người ở|ngồi ở|nó ở",
"hp": "hạnh phúc|hành pháp",
"ntcm": "người thân của mình",
"nmkp": "nhưng mà không phải",
"nccn": "người có chánh niệm",
"ctck": "chúng ta cũng không",
"tmtq": "thành một thói quen",
"ttnl": "tiêu tốn năng lượng",
"ttvd": "tình thương vô điều",
"kk": "khó khăn|kinh khủng",
"cscc": "cuộc sống của chúng",
"qtnl": "quan trọng nhất là",
"mctt": "một cách trực tiếp",
"hdcm": "hành động của mình",
"thcm": "thực hành của mình",
"ctbr": "chúng ta biết rằng",
"nvcc": "nhiệm vụ của chúng",
"cscm": "cuộc sống của mình",
"ctkt": "chúng ta không thể",
"mktn": "mình không thể nào",
"vq": "vượt qua|việc quan",
"kq": "kết quả|không quan",
"ctth": "chúng ta thực hành",
"pttt": "phát triển trí tuệ",
"kbgn": "không bao giờ nghĩ",
"kctk": "khi chúng ta không",
"gntt": "ghi nhận thuần túy",
"tsmk": "tại sao mình không",
"vcqt": "vô cùng quan trọng",
"dtdp": "dưới thời đức phật",
"tttb": "trạng thái tâm bất",
"htkc": "hoàn toàn không có",
"tgkm": "thư giãn khuôn mặt",
"ca": "có ai|cô ấy|cái ảo",
"ctkl": "chúng ta không làm",
"cdcc": "cuộc đời của chúng",
"tctk": "thì chúng ta không",
"tdct": "trong đầu chúng ta",
"ctnt": "chúng ta nhìn thấy",
"mkhb": "mình không hề biết",
"cctk": "của chúng ta không",
"tdcc": "thái độ chân chánh",
"cnct": "con người chúng ta",
"clqg": "chẳng liên quan gì",
"mcht": "một cách hoàn toàn",
"mp": "mình phải|một phần",
"tnmc": "thế nhưng mà chúng",
"kbgm": "không bao giờ mình",
"thmc": "thực hành một cách",
"mccn": "mình có chánh niệm",
"kbts": "không biết tại sao",
"mttt": "một trạng thái tâm",
"ctll": "chúng ta luôn luôn",
"ctph": "chúng ta phải hiểu",
"klqg": "không liên quan gì",
"ckpc": "chứ không phải chỉ",
"ngmd": "những gì mình đang",
"ctnr": "chúng ta nghĩ rằng",
"tknt": "ta không nhìn thấy",
"mkbg": "mình không bao giờ",
"rntk": "rất nhiều thứ khác",
"kbgd": "không bao giờ được",
"cncm": "cách nhìn của mình",
"cktn": "cũng không thể nào",
"mmkb": "mà mình không biết",
"ttbt": "thái tâm bất thiện",
"mttm": "mình trở thành một",
"ctpb": "chúng ta phải biết",
"crnn": "có rất nhiều người",
"ckqt": "cực kỳ quan trọng",
"mctn": "một cách tự nhiên",
"dpnr": "đức phật nói rằng",
"ngct": "những gì chúng ta",
"dvmn": "đối với một người",
"kplc": "không phải là cái",
"hhmn": "hầu hết mọi người",
"ccnt": "có chánh niệm thì",
"ctpl": "chúng ta phải làm",
"mcdg": "một cách đơn giản",
"hb": "hiểu biết|hề biết",
"tctt": "thì chúng ta thấy",
"sncm": "suy nghĩ của mình",
"dgpx": "đánh giá phán xét",
"gcct": "giúp cho chúng ta",
"ctmt": "chúng ta mới thấy",
"mctk": "mà chúng ta không",
"dpmn": "đa phần mọi người",
"nctc": "nào chúng ta cũng",
"mrln": "mình rất là nhiều",
"cdcm": "cuộc đời của mình",
"kytd": "không ý thức được",
"ckpl": "chứ không phải là",
"rlqt": "rất là quan trọng",
"cdct": "cuộc đời chúng ta",
"tttg": "trí tuệ trực giác",
"ccdm": "của cuộc đời mình",
"ql": "quay lại|quy luật",
"mtgt": "một thời gian thì",
"vctp": "vậy chúng ta phải",
"crnd": "có rất nhiều điều",
"mcrn": "mình có rất nhiều",
"dlnn": "đó là những người",
"lnmc": "lúc nào mình cũng",
"cgkc": "cảm giác khó chịu",
"mtct": "mình thì chúng ta",
"mtgs": "một thời gian sau",
"nlnt": "nhiều lần như thế",
"kckn": "không có khả năng",
"ngtd": "những gì thầy dạy",
"ctlv": "chúng ta làm việc",
"mtdh": "một tiếng đồng hồ",
"cttg": "chúng ta thư giãn",
"tpth": "ta phải thực hành",
"ktnl": "không thể nào làm",
"ctlc": "chúng ta lựa chọn",
"ctxd": "chúng ta xác định",
"mlmn": "mình là một người",
"kctt": "khi chúng ta thực",
"ctkd": "chúng ta không đủ",
"ctqs": "chúng ta quan sát",
"ctsk": "chúng ta sẽ không",
"lq": "là quan|liên quan",
"tdlt": "thay đổi liên tục",
"nvcm": "nhiệm vụ của mình",
"bd": "bắt đầu|biết được",
"vmnc": "và mọi người cười",
"nctp": "nên chúng ta phải",
"tvmn": "thầy và mọi người",
"tctp": "thì chúng ta phải",
"scct": "sống của chúng ta",
"nbt": "người bình thường",
"lctk": "là chúng ta không",
"np": "nó phải|nghe pháp",
"cttd": "chúng ta thay đổi",
"nttc": "như thế thì chúng",
"tcnd": "tất cả những điều",
"ctsn": "chúng ta suy nghĩ",
"dhsc": "định hướng sự chú",
"smtg": "sau một thời gian",
"tcmn": "tất cả mọi người",
"pgn": "phật giáo nguyên",
"gnt": "giáo nguyên thủy",
"mr": "mình rất|mình ra",
"cq": "cái quả|có quyền",
"pd": "phật dạy|phải đi",
"ntnm": "như thế nhưng mà",
"cctr": "của chúng ta rất",
"dkpl": "đó không phải là",
"btml": "bản thân mình là",
"cvvn": "chính vì vậy nên",
"dgnt": "đơn giản như thế",
"lmnr": "là một người rất",
"crnt": "có rất nhiều thứ",
"tmtg": "tu một thời gian",
"nlcc": "nó làm cho chúng",
"ctmb": "chúng ta mới bắt",
"tdcm": "thái độ của mình",
"dcdd": "được cái điều đó",
"ttlc": "thu thúc lục căn",
"tnlc": "thế nên là chúng",
"dcdp": "dạy của đức phật",
"mcvt": "một cách vô thức",
"ctpc": "chúng ta phải có",
"bdct": "bắt đầu chúng ta",
"ttcm": "trí tuệ của mình",
"ptnm": "phải tự nhiên mà",
"rlbc": "rất là buồn cười",
"cvtn": "chính vì thế nên",
"vnct": "vậy nên chúng ta",
"lnct": "lúc nào chúng ta",
"ttdn": "từ trước đến nay",
"cmdv": "của mình đối với",
"tnct": "thế nên chúng ta",
"nmtr": "nhưng mà thực ra",
"ttvt": "từ trong vô thức",
"csch": "cuộc sống của họ",
"ctsd": "chúng ta sử dụng",
"mctp": "mà chúng ta phải",
"rlnh": "rất là nguy hiểm",
"vdtl": "việc đầu tiên là",
"qtlv": "quay trở lại với",
"snnt": "suy nghĩ như thế",
"mcha": "một cái hình ảnh",
"vctt": "và chúng ta thấy",
"bncm": "bản ngã của mình",
"dttm": "để trở thành một",
"cdtt": "con đường tu tập",
"kctl": "khi chúng ta làm",
"lmcn": "là một con người",
"lcnt": "làm cho người ta",
"ctts": "chúng ta thực sự",
"mmkh": "mà mình không hề",
"dpct": "đa phần chúng ta",
"nptv": "nó phụ thuộc vào",
"lkbg": "là không bao giờ",
"nktn": "nó không thể nào",
"nmts": "nhưng mà tại sao",
"dlcc": "đó làm cho chúng",
"sthc": "sự thực hành của",
"tvbt": "thức về bản thân",
"kcmc": "không có một cái",
"nxlp": "ngài xá lợi phất",
"chnl": "chẳng hạn như là",
"qgdm": "quan gì đến mình",
"nkbg": "nó không bao giờ",
"ltnt": "liên tục như thế",
"mtgl": "một thời gian là",
"ddct": "dần dần chúng ta",
"btmv": "bản thân mình và",
"nctt": "người có trí tuệ",
"tccn": "ta có chánh niệm",
"sccd": "suốt cả cuộc đời",
"ctcg": "chúng ta cố gắng",
"knct": "khi nào chúng ta",
"cmnt": "của mình như thế",
"hhct": "hầu hết chúng ta",
"tctm": "thì chúng ta mới",
"ktnm": "không thể nào mà",
"mntn": "mình như thế nào",
"nkpl": "nó không phải là",
"tcnc": "tất cả những cái",
"lctp": "là chúng ta phải",
"hrln": "hơn rất là nhiều",
"qttt": "quá trình tu tập",
"ottm": "ở trong tâm mình",
"lcct": "làm cho chúng ta",
"tsct": "tại sao chúng ta",
"ctst": "chúng ta sẽ thấy",
"dcct": "đời của chúng ta",
"tcnt": "tất cả những thứ",
"dkct": "đôi khi chúng ta",
"lddd": "làm được điều đó",
"lqgd": "liên quan gì đến",
"tvtm": "thân và tâm mình",
"ctbd": "chúng ta bắt đầu",
"cmnd": "cả mọi người đều",
"kccg": "không có cái gì",
"ckct": "có khi chúng ta",
"cctl": "của chúng ta là",
"vlct": "vậy là chúng ta",
"cncd": "cả những cái đó",
"ttx": "ta thường xuyên",
"mclm": "một cái là mình",
"cbnc": "cái bản ngã của",
"tcts": "thì chúng ta sẽ",
"rldg": "rất là đơn giản",
"dmln": "đến một lúc nào",
"vr": "và rất|việc rất",
"ntnn": "như thế này này",
"dlnc": "đó là những cái",
"ldcd": "lời dạy của đức",
"tcmv": "tất cả mọi việc",
"rnn": "rất nhiều người",
"vkct": "và khi chúng ta",
"bg": "bây giờ|bao giờ",
"ss": "sâu sắc|so sánh",
"dtct": "đó thì chúng ta",
"lbvc": "là bởi vì chúng",
"mkct": "mà khi chúng ta",
"rc": "ra cái|rằng cái",
"dmnt": "đến mức như thế",
"mctv": "mà chúng ta vẫn",
"nmkc": "nếu mà không có",
"rlnv": "rất là nhiều và",
"nmbv": "nhưng mà bởi vì",
"tntk": "thế này thế kia",
"mnk": "mọi người không",
"ccgd": "cái cảm giác đó",
"tcs": "trong cuộc sống",
"ncdl": "những cái đó là",
"mdnl": "một điều nữa là",
"lkct": "là khi chúng ta",
"mck": "mình cũng không",
"bvct": "bởi vì chúng ta",
"dpbl": "đức phật bảo là",
"vqt": "việc quan trọng",
"ctmn": "cái tâm mình nó",
"tstr": "ta sẽ thấy rằng",
"cmsn": "có một số người",
"dctm": "đó chúng ta mới",
"ntg": "nhiều thời gian",
"dcmd": "độ của mình đối",
"kmct": "khi mà chúng ta",
"stdc": "sự thay đổi của",
"cqt": "cùng quan trọng",
"ktm": "không thoải mái",
"hatt": "hình ảnh tự tạo",
"ntgl": "người ta gọi là",
"nnn": "những người nào",
"cctn": "của chúng ta nó",
"smct": "sao mà chúng ta",
"mctl": "mình có thể làm",
"cctd": "cả chúng ta đều",
"bm": "biết mình|bố mẹ",
"vk": "và khi|và không",
"vnn": "với những người",
"mcrl": "một cách rất là",
"ntnt": "như thế nào thì",
"ctmc": "chúng ta mới có",
"ctcr": "chúng ta có rất",
"kctc": "khi chúng ta có",
"xr": "xong rồi|xảy ra",
"ptd": "phát triển được",
"tcrn": "ta có rất nhiều",
"tnts": "thế nên tại sao",
"kcn": "không chấp nhận",
"qtn": "quan trọng nhất",
"cycc": "chú ý của chúng",
"vcct": "vụ của chúng ta",
"tqt": "trong quá trình",
"obmd": "ở bên miến điện",
"cctv": "của chúng ta và",
"cntd": "cả những thứ đó",
"dqt": "điều quan trọng",
"kbm": "không biết mình",
"dclm": "đấy cũng là một",
"tdrl": "thay đổi rất là",
"tnv": "trách nhiệm với",
"ckb": "cũng không biết",
"ctld": "có thể làm được",
"ldct": "lúc đó chúng ta",
"tcng": "tất cả những gì",
"cgct": "cái gì chúng ta",
"nlcm": "nó làm cho mình",
"hh": "hầu hết|học hỏi",
"vmnt": "về mình như thế",
"rk": "ra khỏi|rất khó",
"mht": "mình hoàn toàn",
"vth": "việc thực hành",
"mpb": "mình phải biết",
"lnv": "làm những việc",
"nsn": "những suy nghĩ",
"dntn": "đó như thế nào",
"btc": "bản thân chúng",
"cgn": "cũng giống như",
"hc": "hành của|họ có",
"cmtd": "cả mọi thứ đều",
"kpc": "không phải chỉ",
"rldd": "rất là dễ dàng",
"mo": "mình ở|một ông",
"mth": "mình thực hành",
"tcd": "trong cuộc đời",
"qth": "quan trọng hơn",
"nnct": "này nọ các thứ",
"rt": "rồi thì|ra thì",
"rlrr": "rất là rõ ràng",
"tcmt": "tất cả mọi thứ",
"ycct": "ý của chúng ta",
"nvn": "người việt nam",
"dpk": "đức phật không",
"ptt": "phát triển trí",
"mkl": "mình không làm",
"kpn": "không phải như",
"nnc": "những người có",
"lbvm": "là bởi vì mình",
"ctcy": "chúng ta chú ý",
"mbm": "mình biết mình",
"nndl": "như nó đang là",
"ncv": "nói chuyện với",
"thd": "thực hành được",
"vnk": "với người khác",
"lcts": "là chúng ta sẽ",
"ddrl": "điều đó rất là",
"kcp": "không cần phải",
"bcmc": "bất cứ một cái",
"nntn": "nó như thế nào",
"thp": "thực hành pháp",
"htcm": "hết tất cả mọi",
"cycm": "chú ý của mình",
"cslc": "có sự lựa chọn",
"odct": "ở đây chúng ta",
"ckp": "chứ không phải",
"tntn": "thế này thế nọ",
"rdmt": "rồi đủ mọi thứ",
"mkt": "mình không thể",
"ltnd": "làm thế nào để",
"rqt": "rất quan trọng",
"ctk": "chúng ta không",
"ccgo": "các cảm giác ở",
"hhtc": "hầu hết tất cả",
"mlnd": "một lúc nào đó",
"sd": "sử dụng|sau đó",
"rr": "rõ ràng|rất rõ",
"lmcd": "là một cách để",
"ba": "bình an|bất an",
"bcln": "bất cứ lúc nào",
"dlct": "đó là chúng ta",
"bcvg": "bất cứ việc gì",
"ctsc": "chúng ta sẽ có",
"kld": "không làm được",
"rlmm": "rất là mạnh mẽ",
"ctcs": "chúng ta có sự",
"ntsm": "nên tại sao mà",
"nnd": "những người đó",
"ot": "ở trong|ở trên",
"ntnv": "như thế nào và",
"nrm": "nghĩ rằng mình",
"dcgc": "được cái gì cả",
"cyhn": "cũng y hệt như",
"pth": "phải thực hành",
"drn": "được rất nhiều",
"hscy": "hướng sự chú ý",
"cnlc": "cái này là cái",
"ldll": "lặp đi lặp lại",
"ac": "ai cũng|ăn cắp",
"cnn": "có những người",
"dq": "đạo quả|đi qua",
"lnn": "là những người",
"nnm": "những người mà",
"nctd": "nó có tác dụng",
"scc": "sống của chúng",
"rnv": "rất nhiều việc",
"mll": "mình luôn luôn",
"mtt": "mình trở thành",
"dtd": "dưới thời đức",
"tdn": "trước đến nay",
"hnk": "hầu như không",
"mlv": "mình làm việc",
"mtnc": "một tí nào cả",
"mcgd": "một cái gì đó",
"vnc": "vậy nên chúng",
"qsd": "quan sát được",
"trk": "thoát ra khỏi",
"rnc": "rất nhiều cái",
"nlmc": "nó là một cái",
"thm": "thực hành một",
"mnn": "một người nào",
"bv": "bởi vì|bảo vệ",
"vb": "về bản|và bắt",
"stkl": "sự tự kỷ luật",
"on": "ở ngoài|ở nhà",
"yhnt": "y hệt như thế",
"ytvb": "ý thức về bản",
"bccg": "bất cứ cái gì",
"li": "lợi ích|là ít",
"hmn": "hết mọi người",
"chk": "có hiểu không",
"cdrl": "cái đó rất là",
"dvnl": "do vậy nên là",
"ntp": "người ta phải",
"mcgc": "một cái gì cả",
"lb": "là bởi|là bắt",
"nclm": "nó chỉ là một",
"mqt": "một quá trình",
"tpt": "ta phát triển",
"yc": "ý của|yêu cầu",
"ngt": "những gì thầy",
"cpn": "cái phiền não",
"mtm": "mình thì mình",
"nln": "nhất là những",
"chn": "chẳng hạn như",
"lcc": "làm cho chúng",
"lqt": "là quan trọng",
"tdh": "tiếng đồng hồ",
"mcs": "một cuộc sống",
"tkp": "ta không phải",
"cdm": "cuộc đời mình",
"rnt": "rất nhiều thứ",
"ctq": "chúng ta quan",
"dkc": "đôi khi chúng",
"nmt": "nhưng mà thực",
"ktn": "không thể nào",
"tck": "ta cũng không",
"ctg": "cái thời gian",
"mpl": "mình phải làm",
"mdl": "mình đang làm",
"tbt": "tâm bất thiện",
"hrn": "hơn rất nhiều",
"ngm": "những gì mình",
"mtq": "một thói quen",
"lqd": "liên quan đến",
"nkp": "nó không phải",
"dpt": "để phát triển",
"kbl": "không biết là",
"kbg": "không bao giờ",
"csc": "cuộc sống của",
"ptv": "phụ thuộc vào",
"mtg": "một thời gian",
"vdt": "việc đầu tiên",
"dkp": "đó không phải",
"kpl": "không phải là",
"tmp": "thì mình phải",
"dcc": "đời của chúng",
"chb": "cái hiểu biết",
"mnd": "mọi người đều",
"ldd": "làm được điều",
"tsc": "tại sao chúng",
"ndd": "những điều đó",
"mmk": "mà mình không",
"mqs": "mình quan sát",
"bnn": "bao nhiêu năm",
"tmct": "ta mới có thể",
"scm": "sống của mình",
"khb": "không hề biết",
"tdp": "thời đức phật",
"mkh": "mình không hề",
"cvn": "cái việc này",
"dvc": "do vậy chúng",
"nll": "nó luôn luôn",
"mcr": "một cách rất",
"bdm": "bắt đầu mình",
"ccl": "chắc chắn là",
"dpn": "đức phật nói",
"vdnl": "ví dụ như là",
"tmm": "thì mình mới",
"sct": "sao chúng ta",
"llc": "luôn luôn có",
"lnm": "lúc nào mình",
"nlcg": "nó là cái gì",
"ttr": "ta thấy rằng",
"kct": "khi chúng ta",
"tnr": "ta nghĩ rằng",
"snc": "suy nghĩ của",
"dkh": "đi kinh hành",
"ddv": "đối diện với",
"snt": "sống như thế",
"vdk": "vô điều kiện",
"ldc": "lúc đó chúng",
"tth": "ta thực hành",
"cmvs": "có một vị sư",
"tll": "ta luôn luôn",
"scyc": "sự chú ý của",
"txv": "tiếp xúc với",
"mst": "mình sẽ thấy",
"pnt": "phải như thế",
"lqg": "liên quan gì",
"tbr": "ta biết rằng",
"cbg": "chưa bao giờ",
"qalh": "quả a la hán",
"smt": "sau một thời",
"kcm": "không có một",
"rdg": "rất đơn giản",
"cha": "cái hình ảnh",
"skb": "sự khác biệt",
"lg": "là gì|làm gì",
"dnt": "được như thế",
"nht": "nó hoàn toàn",
"cvdg": "có vấn đề gì",
"otm": "ở trong mình",
"dpb": "đức phật bảo",
"str": "sẽ thấy rằng",
"tkt": "ta không thể",
"vdgc": "vấn đề gì cả",
"nvc": "nhiệm vụ của",
"dpm": "đức phật mới",
"sth": "sự thực hành",
"mdv": "mình đối với",
"xpt": "xuất phát từ",
"dkm": "đôi khi mình",
"dmc": "được một cái",
"ttd": "từ trước đến",
"ctv": "chúng ta vẫn",
"nlt": "ngay lập tức",
"cmd": "của mình đối",
"nhn": "ngày hôm nay",
"tcp": "ta cũng phải",
"bgd": "bao giờ được",
"ncd": "những cái đó",
"tpb": "ta phải biết",
"ntr": "người ta rất",
"bts": "biết tại sao",
"qsc": "quan sát cái",
"lh": "là họ|là hay",
"hlm": "hoặc là mình",
"lr": "là rất|là rõ",
"mmp": "mà mình phải",
"dgn": "đơn giản như",
"bgn": "bao giờ nghĩ",
"dcm": "đời của mình",
"dtc": "đó thì chúng",
"lnh": "là nguy hiểm",
"lcd": "là con đường",
"cdp": "của đức phật",
"crn": "có rất nhiều",
"dpd": "đức phật dạy",
"vcq": "vô cùng quan",
"phr": "phát hiện ra",
"bsd": "biết sử dụng",
"ddd": "được điều đó",
"htl": "hoàn toàn là",
"smc": "sức mạnh của",
"dtt": "để trở thành",
"lhp": "là hạnh phúc",
"lmp": "là mình phải",
"cvv": "chính vì vậy",
"ddm": "dần dần mình",
"gnl": "giống như là",
"cat": "cái ảo tưởng",
"mvg": "một việc gì",
"ddq": "đắc đạo quả",
"tlm": "tức là mình",
"kcs": "không có sự",
"ldm": "lúc đó mình",
"snd": "suy nghĩ đó",
"dymx": "để ý mà xem",
"cdd": "cái điều đó",
"ytd": "ý thức được",
"rlm": "rất là mạnh",
"dbg": "đến bây giờ",
"plc": "phải là cái",
"mcv": "một cách vô",
"obt": "ở bên trong",
"phv": "phù hợp với",
"slc": "sự lựa chọn",
"cbn": "cái bản ngã",
"lscy": "là sự chú ý",
"tms": "thì mình sẽ",
"vmc": "vào một cái",
"cscy": "có sự chú ý",
"dcg": "được cái gì",
"ltn": "làm thế nào",
"ncs": "người cư sĩ",
"ldg": "là đơn giản",
"cdk": "cho đến khi",
"vbt": "về bản thân",
"dtl": "đầu tiên là",
"tnn": "tự nhiên nó",
"cml": "của mình là",
"mls": "một lúc sau",
"mlm": "mình là một",
"tqs": "ta quan sát",
"cta": "chúng ta ăn",
"omd": "ở miến điện",
"mrl": "mình rất là",
"bvm": "bởi vì mình",
"bcv": "bất cứ việc",
"otc": "ở trong cái",
"ndl": "người đó là",
"thr": "thể hiện ra",
"dpl": "đức phật là",
"dcl": "đấy cũng là",
"lvd": "làm việc đó",
"mqh": "mối quan hệ",
"tdc": "thái độ của",
"tkc": "ta không có",
"tkh": "ta không hề",
"lkc": "là không có",
"rlq": "rất là quan",
"hht": "hầu hết tất",
"qgd": "quan gì đến",
"mdp": "mà đức phật",
"sqs": "sự quan sát",
"vts": "vị thiền sư",
"kcg": "không có gì",
"hnt": "hệt như thế",
"lsn": "là suy nghĩ",
"tvm": "thầy và mọi",
"pp": "phương pháp",
"vnt": "và người ta",
"ckq": "cực kỳ quan",
"ddr": "điều đó rất",
"lvg": "làm việc gì",
"tcl": "thậm chí là",
"std": "sự thay đổi",
"hhm": "hầu hết mọi",
"nbd": "nó bắt đầu",
"thl": "thứ hai là",
"ntl": "như thế là",
"cmt": "cả mọi thứ",
"gq": "giải quyết",
"bvs": "bởi vì sao",
"tst": "ta sẽ thấy",
"mcl": "một cái là",
"lbd": "là bắt đầu",
"lsm": "làm sao mà",
"bcm": "bất cứ một",
"dmt": "đủ mọi thứ",
"hrl": "hơn rất là",
"tkl": "tự kỷ luật",
"qd": "quyết định",
"ltt": "là trí tuệ",
"mtr": "mà thực ra",
"mmc": "mà mình có",
"vnl": "vậy nên là",
"bcl": "bất cứ lúc",
"mvd": "một vấn đề",
"ddl": "điều đó là",
"ntm": "như thế mà",
"cdym": "cứ để ý mà",
"cdr": "cái đó rất",
"vtn": "vì thế nên",
"pcy": "phải chú ý",
"kp": "không phải",
"tpc": "ta phải có",
"rmc": "ra một cái",
"bdc": "bắt đầu có",
"tnd": "thế nào để",
"rrl": "rõ ràng là",
"bdl": "bắt đầu là",
"dlo": "dừng lại ở",
"bdt": "bắt đầu từ",
"cyn": "có ý nghĩa",
"cyh": "cũng y hệt",
"nvl": "như vậy là",
"cgo": "cảm giác ở",
"cgh": "cái gì hết",
"cvg": "cứ việc gì",
"lnd": "lúc nào đó",
"sba": "sự bình an",
"vtk": "vị tỳ khưu",
"bvk": "bởi vì khi",
"cto": "chúng ta ở",
"ddn": "dần dần nó",
"rlt": "rất là tốt",
"otd": "ở trong đó",
"vgd": "việc gì đó",
"tsd": "ta sử dụng",
"rlh": "rất là hay",
"dmm": "đến mức mà",
"htc": "hết tất cả",
"vbd": "và bắt đầu",
"tsl": "thực sự là",
"ovn": "ở việt nam",
"dml": "đó mới là",
"vdn": "ví dụ như",
"qn": "quá nhiều",
"bvh": "bởi vì họ",
"cyc": "chú ý của",
"drl": "đó rất là",
"tcr": "ta có rất",
"cdn": "cái đó nó",
"nlm": "nó là một",
"mq": "mình quan",
"ytv": "ý thức về",
"xp": "xuất phát",
"arl": "ấy rất là",
"vbv": "và bởi vì",
"ocn": "ở chỗ nào",
"dlg": "để làm gì",
"tns": "thì nó sẽ",
"cyd": "chú ý đến",
"lbv": "là bởi vì",
"pg": "phật giáo",
"dcn": "để cho nó",
"mbv": "mà bởi vì",
"ah": "ảnh hưởng",
"cyv": "chú ý vào",
"vld": "và lúc đó",
"cms": "có một số",
"br": "biết rằng",
"rli": "rất là ít",
"dvl": "do vậy là",
"ldl": "lúc đó là",
"rlv": "rất là vô",
"mvs": "một vị sư",
"bvn": "bởi vì nó",
"rlr": "rất là rõ",
"cvs": "các vị sư",
"blm": "ba la mật",
"vdg": "vấn đề gì",
"yhn": "y hệt như",
"cgl": "cái gì là",
"lgc": "làm gì cả",
"dxm": "đi xe máy",
"ha": "hình ảnh",
"ocd": "ở chỗ đó",
"kv": "khác với",
"db": "đặc biệt",
"ks": "kiếp sau",
"rq": "rất quan",
"qs": "quan sát",
"gg": "giữ giới",
"hq": "hiệu quả",
"bb": "buông bỏ",
"alh": "a la hán",
"gk": "gì không",
"bp": "bài pháp",
"pu": "phản ứng",
"nx": "ngày xưa",
"xd": "xác định",
"ka": "không ai",
"ymx": "ý mà xem",
"ng": "những gì",
"xg": "xuất gia",
"scy": "sự chú ý",
"rh": "rất hay",
"dym": "để ý mà",
"sb": "sự bình",
"hs": "hết sức",
"qa": "quần áo",
"bh": "bài học",
"qg": "quan gì",
"qk": "quá khứ",
"hv": "hợp với",
"vg": "việc gì",
"yn": "ý nghĩa",
"sr": "sinh ra",
"qm": "qua một",
"lp": "là phải",
"xv": "xúc với",
"pc": "phải có",
"qh": "quan hệ",
"sq": "sự quan",
"so": "sống ở",
"ar": "ấy rất",
"lx": "là xấu",
"ra": "rằng à",
"gr": "gây ra",
"mx": "mà xem",
"xh": "xã hội",
"yt": "ý thức",
"oa": "ông ấy",
"vi": "vô ích",
"la": "lúc ấy",
"gh": "gì hết",
"vv": "vì vậy",
"aa": "anh ấy",
"rs": "ra sao",
"xm": "xe máy",
"ri": "rất ít",
"yd": "ý đến",
"xl": "xử lý",
"yh": "y hệt",
"ns": "nó sẽ",
"ob": "ở bên",
"al": "ấy là",
"om": "ở một",
"va": "vị ấy",
"yv": "ý vào",
"dy": "để ý",
"lo": "là ở",
};
